site_name: Solcast API Python SDK
site_url: https://solcast.github.io/solcast-api-python-sdk/
site_dir: public
theme:
  name: material
  logo: 'img/logo.png'
  palette:
    primary: black
    accent: yellow

nav:
  - Home: index.md
  - Forecast: forecast.md
  - Live: live.md
  - Historic: historic.md
  - TMY: tmy.md
  - Example Notebooks:
      - notebooks/1.1 Getting Data - Historic Solar Radiation.ipynb
      - notebooks/1.2 Getting Data - TMY in your local timezone.ipynb
      - notebooks/1.3 Getting Data - Make Concurrent Requests.ipynb
      - notebooks/2.1 PVLib - ModelChain with Solcast weather data.ipynb
      - notebooks/3.1 Comparing to Measurements - Timezone and Time Period alignment.ipynb
      - notebooks/3.2 Comparing to Measurements - Quality Controlling and Gap Filling Measurements with Solcast Actuals.ipynb
      - notebooks/3.3 Comparing to Measurements - Accuracy Metrics.ipynb
      - data:
        - notebooks/data/3.1_sample_measurements.csv
        - notebooks/data/3.2_sample_measurements.csv
        - notebooks/data/3.3_sample_forecasts.csv
        - notebooks/data/3.3_sample_measurements.csv
  - API reference:
      - api/client.md
      - api/response.md
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list


plugins:
  - mkdocs-jupyter
  - mkdocstrings:
      enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: false